// Code generated by MockGen. DO NOT EDIT.
// Source: promt.go

// Package mock_promter is a generated GoMock package.
package mock_promter

import (
	gomock "github.com/golang/mock/gomock"
	promter "github.com/meinto/promter"
	reflect "reflect"
)

// MockPromter is a mock of Promter interface
type MockPromter struct {
	ctrl     *gomock.Controller
	recorder *MockPromterMockRecorder
}

// MockPromterMockRecorder is the mock recorder for MockPromter
type MockPromterMockRecorder struct {
	mock *MockPromter
}

// NewMockPromter creates a new mock instance
func NewMockPromter(ctrl *gomock.Controller) *MockPromter {
	mock := &MockPromter{ctrl: ctrl}
	mock.recorder = &MockPromterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPromter) EXPECT() *MockPromterMockRecorder {
	return m.recorder
}

// YesNo mocks base method
func (m *MockPromter) YesNo(label string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "YesNo", label)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// YesNo indicates an expected call of YesNo
func (mr *MockPromterMockRecorder) YesNo(label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "YesNo", reflect.TypeOf((*MockPromter)(nil).YesNo), label)
}

// Select mocks base method
func (m *MockPromter) Select(label string, options []string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", label, options)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Select indicates an expected call of Select
func (mr *MockPromterMockRecorder) Select(label, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockPromter)(nil).Select), label, options)
}

// Text mocks base method
func (m *MockPromter) Text(label string, options ...promter.PromterOptions) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{label}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Text", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Text indicates an expected call of Text
func (mr *MockPromterMockRecorder) Text(label interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{label}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockPromter)(nil).Text), varargs...)
}

// OptionalText mocks base method
func (m *MockPromter) OptionalText(label string, options ...promter.PromterOptions) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{label}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OptionalText", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OptionalText indicates an expected call of OptionalText
func (mr *MockPromterMockRecorder) OptionalText(label interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{label}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OptionalText", reflect.TypeOf((*MockPromter)(nil).OptionalText), varargs...)
}

// URLWithDefault mocks base method
func (m *MockPromter) URLWithDefault(label, defaultValue string, options ...promter.PromterOptions) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{label, defaultValue}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "URLWithDefault", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URLWithDefault indicates an expected call of URLWithDefault
func (mr *MockPromterMockRecorder) URLWithDefault(label, defaultValue interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{label, defaultValue}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLWithDefault", reflect.TypeOf((*MockPromter)(nil).URLWithDefault), varargs...)
}

// URL mocks base method
func (m *MockPromter) URL(label string, options ...promter.PromterOptions) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{label}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "URL", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// URL indicates an expected call of URL
func (mr *MockPromterMockRecorder) URL(label interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{label}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockPromter)(nil).URL), varargs...)
}
